### ISSUE TITLE
gitconfig

### ISSUE THREAD

**Issue by obayemi** [nim65s/dotfiles#1]
Is it really safe to have your github token on your github hosted .gitconfig?

**Comment by nim65s** [comment]
You mean https://github.com/nim65s/dotfiles/blob/master/.gitconfig#L6 ? 

My github token is not really «NOYOUWILLNOTHAVEMYTOKENLOL»

**Comment by obayemi** [comment]
Oh, I didn't thought of reading it ^^", just saw it somewhere in prod, and that it was versioned...
